LangString addOrReinstall ${LANG_ENGLISH} "Repair / reinstall ${PRODUCTNAME}"
LangString alreadyInstalled ${LANG_ENGLISH} "${PRODUCTNAME} is already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Choose Repair to refresh this installation, or Uninstall to remove it."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is running! Please close it first and try again."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is running!$\nClick OK to close it automatically."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose what you want to do with this installation."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to update ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Create desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Install over existing files"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Install over existing files (downgrading without uninstall is disabled)"
LangString failedToKillApp ${LANG_ENGLISH} "Failed to close {{product_name}}. Please close it manually and try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed. Updating to this older version is not recommended. Choose how you want to continue."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "A previous version of ${PRODUCTNAME} is already installed. Choose Update to replace it with ${VERSION}, then click Next."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled for this installer. Please use the graphical installer instead.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to update the existing installation."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Update ${PRODUCTNAME} (recommended)"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "Failed to install WebView2. The app can't run without it. Try restarting the installer."
LangString webview2DownloadError ${LANG_ENGLISH} "Error: Downloading WebView2 failed - $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded successfully"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2 bootstrapper..."
LangString webview2InstallError ${LANG_ENGLISH} "Error: Installing WebView2 failed with exit code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installed successfully"
LangString deleteAppData ${LANG_ENGLISH} "Delete the application data"
